import React, { Fragment, useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { gsap } from "gsap";

import {
  Navbar,
  Menu,
  PageTrans,
  SearchMenu,
  HelpMenu,
  NavArrows,
  Footer,
} from "../components/PageComponents";

const Page = ({ children, next, prev, title, isFoward, isMenu }) => {
  const router = useRouter();

  return (
    <Fragment>
      <Head>
        <title>{title}</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Sid Newman" />
        <link rel="icon" href="../favicon.ico" />
        <link rel="stylesheet" href="../fonts.css" />
      </Head>
      <Navbar next={next} prev={prev} title={title} isMenu={isMenu} />
      <PageTrans isFoward={isFoward} isMenu={isMenu}>
        {children}
      </PageTrans>
      <Menu />
      <SearchMenu />
      <HelpMenu />
      {router.pathname == "/" ? null : <Footer next={next} prev={prev} />}
    </Fragment>
  );
};

export default Page;
